# I. Exploración y preparación del dato  

* Carga del dataset
* Dimensiones
* Tipos de columnas 
* Volumen de registros

In [108]:
import pandas as pd

## DATASET: 1_CLEANBOMBWW2.CSV

>Esta es una version limpia de las bases datos de THOR

In [109]:
# 1. Cargar el dataset (Asegúrate de poner la ruta correcta de tu archivo)
# Si estás en Colab, recuerda subir el archivo antes a la carpeta de la izquierda
df_1_clean_bomb = pd.read_csv('data/1_cleanbombww2.csv', low_memory=False) # low_memory=False para evitar advertencias de tipos de datos mixtos

# 2. Inspección rápida: ¿Qué forma tiene y cómo se llaman las columnas?
print("-------------------------------")
print("--- DATOS BRUTOS DETECTADOS ---")
print("-------------------------------")
print(f"\nTotal de registros históricos: {df_1_clean_bomb.shape[0]:,}")
print(f"Total de variables (columnas): {df_1_clean_bomb.shape[1]:,}\n")

# 3. Sacamos los tipos de datos y valores nulos para ver qué columnas pueden ser útiles
print("--------------------------------------")
print("--- TIPOS DE DATOS Y VALORES NULOS ---")
print("--------------------------------------")
print()
df_1_clean_bomb.info() # info() es una forma rápida de ver el tipo de datos y si hay valores nulos

# 4. Listamos todas las columnas para elegir las mejores para el Dashboard
print()
print("--------------------------------------")
print("--- 5 PRIMERAS FILAS PARA REVISIÓN ---")
print("--------------------------------------")
df_1_clean_bomb.head()

-------------------------------
--- DATOS BRUTOS DETECTADOS ---
-------------------------------

Total de registros históricos: 1,109
Total de variables (columnas): 21

--------------------------------------
--- TIPOS DE DATOS Y VALORES NULOS ---
--------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1109 entries, 0 to 1108
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     1109 non-null   int64
 1   Mission ID                     1109 non-null   int64
 2   Mission Date                   1109 non-null   object
 3   Theater of Operations          1109 non-null   object
 4   Country                        1109 non-null   object
 5   Air Force                      1109 non-null   object
 6   Unit ID                        1109 non-null   object
 7   Aircraft Series                1109 non-null   object
 8   Takeoff Base                   1109 non-null   object
 9   Takeoff Location               1109 non-null   object
 10  Takeoff Latitude               1109 non-null   float64
 11  Takeoff Longitude              1109 non-null   float64
 12  Target Country                 1109 non-null   object
 13  Target City                    1109 non-null   object
 14  Target Latitude                1109 non-null   float64
 15  Target Longitude               1109 non-null   float64
 16  Airborne Aircraft              1109 non-null   float64
 17  Bombing Aircraft               1109 non-null   float64
 18  High Explosives Type           1109 non-null   object
 19  High Explosives Weight (Tons)  1109 non-null   float64
 20  Total Weight (Tons)            1109 non-null   float64
dtypes: float64(8), int64(2), object(11)
memory usage: 182.1+ KB

--------------------------------------
--- 5 PRIMERAS FILAS PARA REVISIÓN ---
--------------------------------------

,Unnamed: 0,Mission ID,Mission Date,Theater of Operations,Country,Air Force,Unit ID,Aircraft Series,Takeoff Base,Takeoff Location,...,Takeoff Longitude,Target Country,Target City,Target Latitude,Target Longitude,Airborne Aircraft,Bombing Aircraft,High Explosives Type,High Explosives Weight (Tons),Total Weight (Tons)
0,0,1,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,PONTE OLIVO AIRFIELD,SICILY,...,14.321464,ITALY,SPADAFORA,38.22,15.37,20.0,20.0,500 LB GP (GP-M43/M64),10.0,10.0
1,1,3,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,PONTE OLIVO AIRFIELD,SICILY,...,14.321464,ITALY,COSENZA,39.27,16.25,18.0,36.0,500 LB GP (GP-M43/M64),9.0,9.0
2,2,4,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,PONTE OLIVO AIRFIELD,SICILY,...,14.321464,ITALY,GIOJA TAURO,38.43,15.90,15.0,15.0,500 LB GP (GP-M43/M64),7.5,7.5
3,3,96,8/16/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,PONTE OLIVO AIRFIELD,SICILY,...,14.321464,ITALY,VILLA SAN GIOVANNI,38.20,15.65,32.0,32.0,500 LB GP (GP-M43/M64),16.0,16.0
4,4,302,8/16/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,PONTE OLIVO AIRFIELD,SICILY,...,14.321464,ITALY,COSENZA,39.27,16.25,4.0,8.0,500 LB GP (GP-M43/M64),2.0,2.0

## DATASET: 2_OPERATIONS.CSV

>Esta base de datos consiste en reportes de misiones de WWII digitalizados. 
>
>Cada registro incluye: fecha, conflicto, localización geográfica y otros datos que conforman una secuencia cronológica de la guerra aérea entre 1939 y 1945. 
>
>Los registros incluyen datos de la Fuerza Aérea de los Estados Unidos y la Real Fuerza Aérea Británica, además de algunas misiones de las fuerzas aéreas australianas, neozelandesas y sudafricanas.

In [110]:
# 1. Cargar el dataset (Asegúrate de poner la ruta correcta de tu archivo)
# Si estás en Colab, recuerda subir el archivo antes a la carpeta de la izquierda
df_2_operations = pd.read_csv('data/2_operations.csv', low_memory=False) # low_memory=False para evitar advertencias de tipos de datos mixtos

# 2. Inspección rápida: ¿Qué forma tiene y cómo se llaman las columnas?
print("-------------------------------")
print("--- DATOS BRUTOS DETECTADOS ---")
print("-------------------------------")
print(f"\nTotal de registros históricos: {df_2_operations.shape[0]:,}")
print(f"Total de variables (columnas): {df_2_operations.shape[1]:,}\n")

# 3. Sacamos los tipos de datos y valores nulos para ver qué columnas pueden ser útiles 
print("--------------------------------------")
print("--- TIPOS DE DATOS Y VALORES NULOS ---")
print("--------------------------------------")
print()
df_2_operations.info() # info() es una forma rápida de ver el tipo de datos y si hay valores nulos

# 4. Listamos todas las columnas para elegir las mejores para el Dashboard
print("--------------------------------------")
print("--- 5 PRIMERAS FILAS PARA REVISIÓN ---")
print("--------------------------------------")
df_2_operations.head()

-------------------------------
--- DATOS BRUTOS DETECTADOS ---
-------------------------------

Total de registros históricos: 178,281
Total de variables (columnas): 46

--------------------------------------
--- TIPOS DE DATOS Y VALORES NULOS ---
--------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178281 entries, 0 to 178280
Data columns (total 46 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Mission ID                             178281 non-null  int64
 1   Mission Date                           178281 non-null  object
 2   Theater of Operations                  175123 non-null  object
 3   Country                                126494 non-null  object
 4   Air Force                              126444 non-null  object
 5   Unit ID                                50913 non-null   object
 6   Aircraft Series                        178165 non-null  object
 7   Callsign                               21 non-null      object
 8   Mission Type                           47186 non-null   object
 9   Takeoff Base                           3383 non-null    object
 10  Takeoff Location                       3338 non-null    object
 11  Takeoff Latitude                       2981 non-null    object
 12  Takeoff Longitude                      2980 non-null    float64
 13  Target ID                              127406 non-null  object
 14  Target Country                         177682 non-null  object
 15  Target City                            176018 non-null  object
 16  Target Type                            146370 non-null  object
 17  Target Industry                        126479 non-null  object
 18  Target Priority                        134720 non-null  object
 19  Target Latitude                        169565 non-null  float64
 20  Target Longitude                       169543 non-null  float64
 21  Altitude (Hundreds of Feet)            120826 non-null  float64
 22  Airborne Aircraft                      82242 non-null   float64
 23  Attacking Aircraft                     125108 non-null  float64
 24  Bombing Aircraft                       81612 non-null   float64
 25  Aircraft Returned                      133 non-null     float64
 26  Aircraft Failed                        247 non-null     float64
 27  Aircraft Damaged                       38 non-null      float64
 28  Aircraft Lost                          158 non-null     float64
 29  High Explosives                        34737 non-null   float64
 30  High Explosives Type                   41945 non-null   object
 31  High Explosives Weight (Pounds)        2021 non-null    object
 32  High Explosives Weight (Tons)          146201 non-null  float64
 33  Incendiary Devices                     3283 non-null    float64
 34  Incendiary Devices Type                5519 non-null    object
 35  Incendiary Devices Weight (Pounds)     356 non-null     float64
 36  Incendiary Devices Weight (Tons)       25732 non-null   float64
 37  Fragmentation Devices                  5768 non-null    float64
 38  Fragmentation Devices Type             5765 non-null    object
 39  Fragmentation Devices Weight (Pounds)  194 non-null     float64
 40  Fragmentation Devices Weight (Tons)    16902 non-null   float64
 41  Total Weight (Pounds)                  2119 non-null    float64
 42  Total Weight (Tons)                    166508 non-null  float64
 43  Time Over Target                       689 non-null     object
 44  Bomb Damage Assessment                 104 non-null     object
 45  Source ID                              174236 non-null  float64
dtypes: float64(22), int64(1), object(23)
memory usage: 62.6+ MB
--------------------------------------
--- 5 PRIMERAS FILAS PARA REVISIÓN ---
--------------------------------------

,Mission ID,Mission Date,Theater of Operations,Country,Air Force,Unit ID,Aircraft Series,Callsign,Mission Type,Takeoff Base,...,Incendiary Devices Weight (Tons),Fragmentation Devices,Fragmentation Devices Type,Fragmentation Devices Weight (Pounds),Fragmentation Devices Weight (Tons),Total Weight (Pounds),Total Weight (Tons),Time Over Target,Bomb Damage Assessment,Source ID
0,1,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN
1,2,8/15/1943,PTO,USA,5 AF,400 BS,B24,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,9366.0
2,3,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN
3,4,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,7.5,NaN,NaN,NaN
4,5,8/15/1943,PTO,USA,5 AF,321 BS,B24,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,22585.0

##  DATASET: 3_THOR_WWII_AIRCRAFT_GLOSS.CSV
>**Theater History of Operations (THOR)** es una base de datos meticulosamente elaborada sobre bombardeos aéreos históricos desde la Primera Guerra Mundial hasta la Guerra de Vietnam. 
>
>El valor de THOR es inmenso y ya ha demostrado su utilidad para *encontrar munición sin explotar en el sudeste asiático y mejorar las tácticas de combate de la Fuerza Aérea*. Nuestro objetivo es observar el alcance del debate público y la innovación en torno a estos datos.
>
>Este conjunto de datos combina informes de misiones en papel digitalizados de la Segunda Guerra Mundial. Se puede buscar por `fecha`, `conflicto`, `ubicación geográfica` y `más de 60 elementos de datos` adicionales para reconstruir la secuencia cronológica de la guerra aérea entre 1939 y 1945. 
>
>Los registros incluyen datos de la Fuerza Aérea de los Estados Unidos y la Real Fuerza Aérea Británica, así como de algunas misiones de las fuerzas aéreas de Australia, Nueva Zelanda y Sudáfrica.
>

In [111]:
# 1. Cargar el dataset (Asegúrate de poner la ruta correcta de tu archivo)
# Si estás en Colab, recuerda subir el archivo antes a la carpeta de la izquierda
df_3_thor_aircraft = pd.read_csv('data/3_thor_wwii_aircraft_gloss.csv', low_memory=False) # low_memory=False para evitar advertencias de tipos de datos mixtos

# 2. Inspección rápida: ¿Qué forma tiene y cómo se llaman las columnas?
print("-------------------------------")
print("--- DATOS BRUTOS DETECTADOS ---")
print("-------------------------------")
print(f"\nTotal de registros históricos: {df_3_thor_aircraft.shape[0]:,}")
print(f"Total de variables (columnas): {df_3_thor_aircraft.shape[1]:,}\n")

# 3. Sacamos los tipos de datos y valores nulos para ver qué columnas pueden ser útiles 
print("--------------------------------------")
print("--- TIPOS DE DATOS Y VALORES NULOS ---")
print("--------------------------------------")
print()
df_3_thor_aircraft.info() # info() es una forma rápida de ver el tipo de datos y si hay valores nulos


# 4. Listamos todas las columnas para elegir las mejores para el Dashboard
print("--------------------------------------")
print("--- 5 PRIMERAS FILAS PARA REVISIÓN ---")
print("--------------------------------------")
df_3_thor_aircraft.head()

-------------------------------
--- DATOS BRUTOS DETECTADOS ---
-------------------------------

Total de registros históricos: 52
Total de variables (columnas): 6

--------------------------------------
--- TIPOS DE DATOS Y VALORES NULOS ---
--------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gloss_id       52 non-null     int64
 1   aircraft       52 non-null     object
 2   name           52 non-null     object
 3   full_name      52 non-null     object
 4   aircraft_type  52 non-null     object
 5   hyperlink      52 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.6+ KB
--------------------------------------
--- 5 PRIMERAS FILAS PARA REVISIÓN ---
--------------------------------------

,gloss_id,aircraft,name,full_name,aircraft_type,hyperlink
0,1,A20,A20,Douglas A-20 Havoc,Boston Light Bomber / Night-Fighter,http://militaryfactory.com/aircraft/detail.asp...
1,2,A24,A24,Douglass A-24 Banshee,Dive Bomber / Reconnaissance,http://militaryfactory.com/aircraft/detail.asp...
2,3,A26,A26,Douglas A-26 Invader,Medium Bomber / Heavy Assault,http://militaryfactory.com/aircraft/detail.asp...
3,4,A36,A36,North American A-36 Apache (Invader),Ground Attack / Dive Bomber,http://militaryfactory.com/aircraft/detail.asp...
4,5,ALBA,Albacore,Fairey Albacore,Naval Torpedo Bomber,http://militaryfactory.com/aircraft/detail.asp...

## DATASET: 4_THOR_WWII_DATA_CLEAN.CSV

In [112]:
df_4_thor_data_clean = pd.read_csv('data/4_thor_wwii_data_clean.csv', low_memory=False) # low_memory=False para evitar advertencias de tipos de datos mixtos
# 2. Inspección rápida: ¿Qué forma tiene y cómo se llaman las columnas?
print("-------------------------------")
print("--- DATOS BRUTOS DETECTADOS ---")
print("-------------------------------")
print(f"\nTotal de registros históricos: {df_4_thor_data_clean.shape[0]:,}")
print(f"Total de variables (columnas): {df_4_thor_data_clean.shape[1]:,}\n")

# 3. Sacamos los tipos de datos y valores nulos para ver qué columnas pueden ser útiles 
print("--------------------------------------")
print("--- TIPOS DE DATOS Y VALORES NULOS ---")
print("--------------------------------------")
print()
df_4_thor_data_clean.info() # info() es una forma rápida de ver el tipo de datos y si hay valores nulos

# 4. Listamos todas las columnas para elegir las mejores para el Dashboard
print("--------------------------------------")
print("--- 5 PRIMERAS FILAS PARA REVISIÓN ---")
print("--------------------------------------")
df_4_thor_data_clean.head()

-------------------------------
--- DATOS BRUTOS DETECTADOS ---
-------------------------------

Total de registros históricos: 178,281
Total de variables (columnas): 62

--------------------------------------
--- TIPOS DE DATOS Y VALORES NULOS ---
--------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178281 entries, 0 to 178280
Data columns (total 62 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   wwii_id                   178281 non-null  int64
 1   master_index_number       174236 non-null  float64
 2   msndate                   178281 non-null  object
 3   theater                   175123 non-null  object
 4   naf                       126444 non-null  object
 5   country_flying_mission    126494 non-null  object
 6   tgt_country_code          129357 non-null  float64
 7   tgt_country               177682 non-null  object
 8   tgt_location              176018 non-null  object
 9   tgt_type                  146369 non-null  object
 10  tgt_id                    127401 non-null  float64
 11  tgt_industry_code         127907 non-null  float64
 12  tgt_industry              126479 non-null  object
 13  source_latitude           168826 non-null  object
 14  source_longitude          168821 non-null  object
 15  latitude                  169565 non-null  float64
 16  longitude                 169543 non-null  float64
 17  unit_id                   50913 non-null   object
 18  mds                       178165 non-null  object
 19  aircraft_name             178142 non-null  object
 20  msn_type                  47185 non-null   float64
 21  tgt_priority              134716 non-null  object
 22  tgt_priority_explanation  87932 non-null   object
 23  ac_attacking              125114 non-null  float64
 24  altitude                  120822 non-null  float64
 25  altitude_feet             65736 non-null   float64
 26  number_of_he              34738 non-null   float64
 27  type_of_he                41946 non-null   object
 28  lbs_he                    2021 non-null    float64
 29  tons_of_he                146201 non-null  float64
 30  number_of_ic              3278 non-null    float64
 31  type_of_ic                5519 non-null    object
 32  lbs_ic                    356 non-null     float64
 33  tons_of_ic                25738 non-null   float64
 34  number_of_frag            5762 non-null    float64
 35  type_of_frag              5765 non-null    object
 36  lbs_frag                  194 non-null     float64
 37  tons_of_frag              16908 non-null   float64
 38  total_lbs                 2118 non-null    float64
 39  total_tons                166509 non-null  float64
 40  takeoff_base              3379 non-null    object
 41  takeoff_country           3338 non-null    object
 42  takeoff_latitude          2980 non-null    float64
 43  takeoff_longitude         2980 non-null    float64
 44  ac_lost                   157 non-null     float64
 45  ac_damaged                38 non-null      float64
 46  ac_airborne               82248 non-null   float64
 47  ac_dropping               81612 non-null   float64
 48  time_over_target          684 non-null     object
 49  sighting_method_code      98340 non-null   object
 50  sighting_explanation      43971 non-null   object
 51  bda                       104 non-null     object
 52  callsign                  21 non-null      object
 53  rounds_ammo               1 non-null       float64
 54  spares_return_ac          133 non-null     float64
 55  wx_fail_ac                186 non-null     float64
 56  mech_fail_ac              42 non-null      float64
 57  misc_fail_ac              82 non-null      float64
 58  target_comment            53 non-null      object
 59  mission_comments          19 non-null      object
 60  source                    88 non-null      object
 61  database_edit_comments    562 non-null     object
dtypes: float64(32), int64(1), object(29)
memory usage: 84.3+ MB
--------------------------------------
--- 5 PRIMERAS FILAS PARA REVISIÓN ---
--------------------------------------

,wwii_id,master_index_number,msndate,theater,naf,country_flying_mission,tgt_country_code,tgt_country,tgt_location,tgt_type,...,callsign,rounds_ammo,spares_return_ac,wx_fail_ac,mech_fail_ac,misc_fail_ac,target_comment,mission_comments,source,database_edit_comments
0,1,NaN,1943-08-15,MTO,12 AF,USA,13.0,ITALY,SPADAFORA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4285,20028.0,1945-02-20,PTO,5 AF,USA,NaN,PHILIPPINE ISLANDS,PUERTA PRINCESA,UNIDENTIFIED TARGET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,1943-08-15,MTO,12 AF,USA,13.0,ITALY,COSENZA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,1943-08-15,MTO,12 AF,USA,13.0,ITALY,GIOJA TAURO,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
4,8167,14639.0,1945-02-23,PTO,5 AF,USA,NaN,PHILIPPINE ISLANDS,BALETE PASS,WOODED AREA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## DATASET: 5_THOR_WWII_WEAPON_GLOSS.CSV

In [113]:
df_5_thor_weapon = pd.read_csv('data/5_thor_wwii_weapon_gloss.csv', low_memory=False) # low_memory=False para evitar advertencias de tipos de datos mixtos
# 2. Inspección rápida: ¿Qué forma tiene y cómo se llaman las columnas?
print("-------------------------------")
print("--- DATOS BRUTOS DETECTADOS ---")
print("-------------------------------")
print(f"\nTotal de registros históricos: {df_5_thor_weapon.shape[0]}")
print(f"Total de variables (columnas): {df_5_thor_weapon.shape[1]}\n")

# 3. Sacamos los tipos de datos y valores nulos para ver qué columnas pueden ser útiles 
print("--------------------------------------")
print("--- TIPOS DE DATOS Y VALORES NULOS ---")
print("--------------------------------------")
print()
df_5_thor_weapon.info() # info() es una forma rápida de ver el tipo de datos y si hay valores nulos

# 4. Listamos todas las columnas para elegir las mejores para el Dashboard
print("--- 5 PRIMERAS FILAS PARA REVISIÓN  ---")
df_5_thor_weapon.head()

-------------------------------
--- DATOS BRUTOS DETECTADOS ---
-------------------------------

Total de registros históricos: 59
Total de variables (columnas): 8

--------------------------------------
--- TIPOS DE DATOS Y VALORES NULOS ---
--------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rn                  59 non-null     int64
 1   country             59 non-null     object
 2   weapon_name         59 non-null     object
 3   weapon_type         26 non-null     object
 4   weapon_class        59 non-null     object
 5   number_of_bomblets  1 non-null      float64
 6   alt_weapon_name     39 non-null     object
 7   weapon_description  59 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 3.8+ KB
--- 5 PRIMERAS FILAS PARA REVISIÓN  ---

,rn,country,weapon_name,weapon_type,weapon_class,number_of_bomblets,alt_weapon_name,weapon_description
0,1,USA,10 lb Incendiary,NaN,IC,NaN,AN-M67 or AN-M69,10 lb Incendiary that used White Phosphorous o...
1,2,USA,100 lb Incendiary,NaN,IC,NaN,M47A2,100 lb M47A2 Incendiary usually loaded with ge...
2,3,USA,100 lb WP (White Phosphrous),NaN,IC,NaN,M47A2,100 lb M47A2 Smoke bomb
3,4,USA,1000 lb aux fuel tank Incendiary,NaN,IC,NaN,NaN,1000 lb Auxiliary fuel tank. When used as ince...
4,5,USA,136 lb (38x4 Clusters) I-M6,I-M6,IC,NaN,M6,M6 Cluster containing 38 AN-M50 incendiary bom...

# II. Acotación histórica y Estadística

## DATASET 1: df_1_clean_bomb

Nos encontramos con que este dataset sólo nos muestra 1 misión en Francia. 

>Este dataset se encuentra muy sesgado, ya que se centra en el **MTO (Mediterranean Theater of Operations)**, que recoge datos de las campañas de Italia y Sicilia princpialmente. 

La `Target_City` tiene coordenadas [**44 00 N 001 00 E**](https://share.google/pBIwTo4jbPy90rJKC) que no se corresponden con lo que estamos buscando, por tanto,  lo desechamos para nuestro estudio.

In [114]:
# ==========================================
# PASO 2.1: ACOTACIÓN HISTÓRICA Y ESTADÍSTICA
# ==========================================

# 1. Filtramos para quedarnos únicamente con Francia en 1944
df_normandia_1 = df_1_clean_bomb[(df_1_clean_bomb['Target Country'].str.upper() == 'FRANCE') & (df_1_clean_bomb['Mission Date'].astype(str).str.contains('1944'))]

print("--- CONTROL DE SEGMENTACIÓN (A.D.I.) ---")
print(f"Misiones totales en el dataset: {df_1_clean_bomb.shape[0]}")
print(f"Misiones identificadas en Francia durante 1944: {df_normandia_1.shape[0]}\n")

# 2. Análisis Estadístico Descriptivo de Variables Categóricas
print("--- TOP 5 CIUDADES CON MAYOR IMPACTO PATRIMONIAL ---")
print(df_normandia_1['Target City'].value_counts().head(5))

print("\n--- AVIONES MÁS UTILIZADOS EN LAS OPERACIONES ---")
print(df_normandia_1['Aircraft Series'].value_counts().head(5))

# 3. Análisis Estadístico Descriptivo de Variables Numéricas
print("\n--- ANÁLISIS DE CARGA DE IMPACTO (TONELADAS) ---")
print(df_normandia_1['Total Weight (Tons)'].describe())

--- CONTROL DE SEGMENTACIÓN (A.D.I.) ---
Misiones totales en el dataset: 1109
Misiones identificadas en Francia durante 1944: 1

--- TOP 5 CIUDADES CON MAYOR IMPACTO PATRIMONIAL ---
Target City
44 00 N 001 00 E    1
Name: count, dtype: int64

--- AVIONES MÁS UTILIZADOS EN LAS OPERACIONES ---
Aircraft Series
A36    1
Name: count, dtype: int64

--- ANÁLISIS DE CARGA DE IMPACTO (TONELADAS) ---
count    1.0
mean     3.0
std      NaN
min      3.0
25%      3.0
50%      3.0
75%      3.0
max      3.0
Name: Total Weight (Tons), dtype: float64

## DATASET 2: df_2_operations

Este dataset nos muestra 15.270 misiones realizadas en Francia. 

En este dataset encontramos dos cosas llamativas:

* Impacto Geográfico

1. **El Impacto Geográfico (Variables Categóricas)**: 
    Brest (459) y St. Lô (404): Encabezan el ranking. Para tu empresa de patrimonio, esto es la justificación científica de inversión. Le dirás al comité: «Los datos demuestran que las misiones se concentraron críticamente en Brest y Saint-Lô; por ende, nuestros esfuerzos de escaneo 3D y arqueología militar de búnkeres prioritarios deben establecerse allí».
2. **Anomalía / Limpieza profunda**: Te aparece la ciudad UNKNOWN con 299 registros. Esto es genial para documentar que el dataset real tiene "ruido" y que tu software deberá filtrar los nombres desconocidos en la visualización.

* Anomalías detectadas

    * **El "Anómalo" de las Toneladas (Variables Numéricas)**: El valor máximo (`max`) de toneladas tiradas en una misión es 999.0 toneladas. Esto es un "outlier" (un valor extremo) o muy probablemente un código de error de registro en la época (un "placeholder" típico de la informática antigua cuando no sabían el dato exacto).
    * La Media es 46.7 toneladas, pero la Mediana (el 50%) es 33 toneladas. Al ser la media bastante mayor que la mediana, demuestras que hay misiones masivas muy destructivas que empujan el promedio hacia arriba.

In [115]:
# ==========================================
# PASO 2.1: ACOTACIÓN HISTÓRICA Y ESTADÍSTICA
# ==========================================

# 1. Filtramos para quedarnos únicamente con Francia en 1944
df_normandia_2 = df_2_operations[(df_2_operations['Target Country'].str.upper() == 'FRANCE') & (df_2_operations['Mission Date'].astype(str).str.contains('1944'))]

print("--- CONTROL DE SEGMENTACIÓN (A.D.I.) ---")
print(f"Misiones totales en el dataset: {df_2_operations.shape[0]:,}")
print(f"Misiones identificadas en Francia durante 1944: {df_normandia_2.shape[0]:,}\n")

# 2. Análisis Estadístico Descriptivo de Variables Categóricas
print("--- TOP 5 CIUDADES CON MAYOR IMPACTO PATRIMONIAL ---")
print(df_normandia_2['Target City'].value_counts().head(5))

print("\n--- AVIONES MÁS UTILIZADOS EN LAS OPERACIONES ---")
print(df_normandia_2['Aircraft Series'].value_counts().head(5))

# 3. Análisis Estadístico Descriptivo de Variables Numéricas
print("\n--- ANÁLISIS DE CARGA DE IMPACTO (TONELADAS) ---")
print(df_normandia_2['Total Weight (Tons)'].describe())

--- CONTROL DE SEGMENTACIÓN (A.D.I.) ---
Misiones totales en el dataset: 178,281
Misiones identificadas en Francia durante 1944: 15,270

--- TOP 5 CIUDADES CON MAYOR IMPACTO PATRIMONIAL ---
Target City
BREST            459
ST LO            404
UNKNOWN          299
METZ             279
PAS DE CALAIS    269
Name: count, dtype: int64

--- AVIONES MÁS UTILIZADOS EN LAS OPERACIONES ---
Aircraft Series
B17     3939
B26     3591
B24     3516
HVY     1050
GB17    1009
Name: count, dtype: int64

--- ANÁLISIS DE CARGA DE IMPACTO (TONELADAS) ---
count    15135.000000
mean        46.724678
std         77.121534
min          0.000000
25%         15.000000
50%         33.000000
75%         56.000000
max        999.000000
Name: Total Weight (Tons), dtype: float64

## DATASET 3: df_3_thor_aircraft

Utilizamos este dataset para "traducir" la columna `Aircraft Series` del dataset inicial **2_operations.csv** y poder tener los nombres completos de los modelos de avión.

In [116]:
# ==========================================================
# PASO 2.2: ENRIQUECIMIENTO DE DATOS (A.D.I. CORE)
# ==========================================================

# 1. Cargamos el glosario de aviones
# df_3_thor_aircraft = pd.read_csv("3_thor_wwii_aircraft_gloss.csv")

# 2. Fusionamos nuestro dataset de Francia con el glosario usando como puente la columna del avión
# En df_normandia_2 se llama 'Aircraft Series' y en el glosario se llama 'aircraft'
df_enriquecido = pd.merge(
    df_normandia_2, # nuestro dataset acotado a Francia 1944
    df_3_thor_aircraft, # el glosario de aviones
    left_on='Aircraft Series', # la columna del avión en nuestro dataset
    right_on='aircraft', # la columna del avión en el glosario
    how='left' # left join para no perder misiones aunque no encontremos el avión en el glosario
)

# 3. Creamos una columna limpia para el nombre del avión (si no encuentra el glosario, deja el original)
df_enriquecido['Avion_Nombre_Completo'] = df_enriquecido['full_name'].fillna(df_enriquecido['Aircraft Series'])

# 4. EXPORTACIÓN CRÍTICA: Guardamos el archivo final que alimentará Power BI y Streamlit
df_enriquecido.to_csv("adi_normandia_final.csv", index=False)

print("🚀 ¡Fusión completada con éxito por A.D.I.!")
print(f"Archivo 'adi_normandia_final.csv' generado listo para maquetar.")

🚀 ¡Fusión completada con éxito por A.D.I.!
Archivo 'adi_normandia_final.csv' generado listo para maquetar.

## DATASET 4: df_4_thor_data_clean

Vamos a analizar este Top 5 de Objetivos Militaries con la mentalidad de una Consultora de Patrimonio:

1. AIRDROME (2.157 impactos) 🛩️
Qué significa: Aeródromos, pistas de despegue y hangares de la Luftwaffe (el ejército del aire alemán) en Francia.

Uso para tu proyecto: Los aeródromos militares de la Segunda Guerra Mundial suelen tener búnkeres de mando, torres de control fortificadas y refugios de hormigón. Esto justifica que A.D.I. lance una línea de negocio específica para maquetación 3D y conservación de antiguas bases aéreas olvidadas.

2. UNIENTIFIED TARGET y UNIDENTIFIED TARGET (1.181 + 574 = 1.755 impactos) 🔍
Qué significa: ¡Fíjate que viene escrito de dos formas distintas por errores de mecanografía de la época! Al sumarlos, es el segundo objetivo más común. Eran misiones secretas o posiciones defensivas espontáneas que los pilotos atacaban en el frente.

Uso para tu proyecto (¡Tus búnkeres ocultos!): En arqueología militar, un "objetivo no identificado" en 1944 suele ser hoy en día un búnker camuflado en el bosque, una batería de artillería enterrada o un nido de ametralladoras que los aliados detectaron sobre la marcha. Para A.D.I., esta es la justificación perfecta para venderle a los gobiernos servicios de "Arqueología de Predicción" usando algoritmos para descubrir qué había realmente ahí.

3. CITY AREA (539 impactos) 🏘️
Qué significa: Bombardeos tácticos sobre centros urbanos clave para cortar las líneas de suministro alemanas (como Caen o Saint-Lô).

Uso para tu proyecto: Justifica el análisis del patrimonio histórico urbano y la reconstrucción digital de ciudades medievales francesas que fueron destruidas durante la liberación.

In [ ]:
# ==========================================================
# PASO 2.3: AUDITORÍA DEL DATASET 4 (A.D.I. ARQUEOLOGÍA)
# ==========================================================

# 2. Filtramos Francia en 1944 (aquí la columna de fecha se llama 'msndate')
df_4_thor_data_clean['tgt_country'] = df_4_thor_data_clean['tgt_country'].astype(str).str.upper()
df_4_normandia = df_4_thor_data_clean[(df_4_thor_data_clean['tgt_country'] == 'FRANCE') & (df_4_thor_data_clean['msndate'].astype(str).str.contains('1944'))]

print("--- AUDITORÍA DATASET 4 (A.D.I.) ---")
print(f"Misiones identificadas en Francia (1944): {df_4_normandia.shape[0]:,}\n")

# 3. Descubrimos qué infraestructuras militares (búnkeres, bases) fueron atacadas
print("--- TOP 5 TIPOS DE OBJETIVOS MILITARES (PATRIMONIO) ---")
print(df_4_normandia['tgt_type'].value_counts().head(5))

--- AUDITORÍA DATASET 4 (A.D.I.) ---
Misiones identificadas en Francia (1944): 15,270

--- TOP 5 TIPOS DE OBJETIVOS MILITARES (PATRIMONIO) ---
tgt_type
AIRDROME               2157
UNIENTIFIED TARGET     1181
UNIDENTIFIED TARGET     574
CITY AREA               539
TACTICAL TARGETS        465
Name: count, dtype: int64

## DATASET 5: df_5_thor_weapon

Glosario de Armamento

In [119]:
# ==========================================================
# PASO 2.3: ENRIQUECIMIENTO FINAL CON EL GLOSARIO DE ARMAS
# ==========================================================

# 1. Cargamos tu archivo estrella de Normandía (el que guardamos en el Paso 2.2)
df_normandia = pd.read_csv("adi_normandia_final.csv")

# 2. Cargamos el diccionario de armas (Dataset 5)
df_5_thor_weapon = pd.read_csv("data/5_thor_wwii_weapon_gloss.csv")

print("--- CONEXIÓN DE ARCHIVOS REALES ---")
print(f"Misiones en Normandía cargadas: {df_normandia.shape[0]}")
print(f"Tipos de armas en el glosario: {df_5_thor_weapon.shape[0]}\n")

# 3. LA FUSIÓN: Cruzamos tus misiones con el glosario de armas
# En tu archivo se llama 'High Explosives Type' y en el glosario 'weapon_name'
df_master = pd.merge(
    df_normandia,
    df_5_thor_weapon[['weapon_name', 'weapon_type', 'weapon_class', 'weapon_description']],
    left_on='High Explosives Type',
    right_on='weapon_name',
    how='left'  # Para no borrar ninguna misión aunque la bomba no esté en el glosario
)

# 4. LIMPIEZA: Si alguna misión no encuentra su bomba en el glosario, le ponemos un texto genérico
df_master['weapon_type'] = df_master['weapon_type'].fillna('HE (High Explosive)')
df_master['weapon_description'] = df_master['weapon_description'].fillna('Bomba estándar de demolición aérea de alta intensidad')

# 5. EXPORTACIÓN MAESTRA: Guardamos el archivo FINAL ABSOLUTO de tu proyecto
df_master.to_csv("adi_dataset_master.csv", index=False)

print("🏆 ¡ENHORABUENA ELENA! TODO EL MOTOR DE DATOS ESTÁ CERRADO.")
print(f"Se ha creado 'adi_dataset_master.csv' con {df_master.shape[0]} filas.")
print("Este único archivo contiene: Francia 1944 + Nombre de Aviones + Descripción de Bombas.")

--- CONEXIÓN DE ARCHIVOS REALES ---
Misiones en Normandía cargadas: 15270
Tipos de armas en el glosario: 59

🏆 ¡ENHORABUENA ELENA! TODO EL MOTOR DE DATOS ESTÁ CERRADO.
Se ha creado 'adi_dataset_master.csv' con 15270 filas.
Este único archivo contiene: Francia 1944 + Nombre de Aviones + Descripción de Bombas.